baseURL = 'https://dudung.github.io/to'
languageCode = 'en-us'
title = 'text only'
theme = 'default'

enableEmoji = true

#disableKinds = ["taxonomyTerm"]

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"


[[menu.main]]
  name = 'Home'
  weight = 1
  identifier = 'home'
  url = '/'
#[[menu.main]]
#  name = 'Posts'
#  weight = 2
#  identifier = 'posts'
#  url = '/posts/'
#[[menu.main]]
#  name = 'Tags'
#  weight = 3
#  identifier = 'tags'
#  url = '/tags/'
#[[menu.main]]
#  name = 'About'
#  weight = 4
#  identifier = 'about'
#  url = '/about/'
